import AboutPage from './AboutPage'
import CartPage from './CartPage'
import ContactPage from './ContactPage'
import DefaultPage from './DefaultPage'
import HomePage from './HomePage'
import ProductsPage from './ProductsPage'
import SingleProductPage from './SingleProductPage'
import SignupPage from './SignupPage'
import LoginPage from './LoginPage'
export { AboutPage, CartPage, ContactPage, DefaultPage, HomePage, ProductsPage, SingleProductPage, SignupPage, LoginPage };
